### ISSUE TITLE
nginx: [emerg] "keepalive_timeout" directive invalid value in /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by s2074135** [mriedmann/humhub-docker#149]
Hi 

Today I tried to upgrade my humhub-docker image from version 1.6.2 to version 1.6.3. Unfortunately, the new container keeps crashing with the following error message:

>  _nginx: [emerg] "keepalive_timeout" directive invalid value in /etc/nginx/nginx.conf:29_

Returning to the old version (1.6.2) resolves the problem. 

When looking at the /etc/nginx/nginx.conf config file at line 29 I see the following statement:

`    keepalive_timeout  ${NGINX_KEEPALIVE_TIMEOUT};`

In my case, the variable $NGINX_KEEPALIVE_TIMEOUT should be replaced by a default value of 65, as I have not defined said variable in my docker-compose.yml file.

I tried to emulate the problem by executing the following statements manually in the running 1.6.3 container:

```
export NGINX_KEEPALIVE_TIMEOUT=65
defined_envs=$(printf "\${%s} " $(env | grep -E "^NGINX_.*" | cut -d= -f1))
envsubst "$defined_envs" </etc/nginx/nginx.conf >/tmp/nginx.conf
```

The variable does not get set correctly in /tmp/nginx.conf. I also tried to set it explicitly in docker-compose.yml, with the same result. The problem pertains as well to other variables in /etc/nginx.nginx.conf such as NGINX_CLIENT_MAX_BODY_SIZE.

I am a bit at a loss on what to do here. I will consider host mounting nginx.conf and run with a static configuration if everything else fails.

Anyone seen this error before or know what I could investigate next?

Thank you.

Thomas

**Comment by mriedmann** [comment]
We will try to investigate that as soon as possible. Sorry for the inconvenience.

Short question: Is https://github.com/mriedmann/humhub-docker/issues/148 a duplicate of this?

**Comment by s2074135** [comment]
> We will try to investigate that as soon as possible. Sorry for the inconvenience.
> 
> Short question: Is #148 a duplicate of this?

Yes, sorry. I closed #148

**Comment by s2074135** [comment]
Correction to my initial post:

> The variable does not get set correctly in /tmp/nginx.conf. I also tried to set it explicitly in docker-compose.yml, with the same result. 

envsubst **does** pick up the variable if it is defined in docker-compose.yml and envsubst ist executed manually from within the container. But when I let entrypoint (docker-compose up) to do the work, it is still not set in /etc/nginix/nginix.conf

**Comment by mriedmann** [comment]
ok very interesting. I know this error but I thought I have fixed it. Can you please provide the output from the entrypoint-script? Currently I am not able to reconstruct the problem. Maybe you can also provide your affected docker-compose file? Would be a big help to find the problem. Thx.

**Comment by s2074135** [comment]
@mriedmann thank you for your offer to help. Version 1.6.3:

/ # cat /etc/nginx/nginx.conf 
```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
error_log  /dev/stderr  notice;
#error_log  logs/error.log  info;

pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  /dev/stdout  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  ${NGINX_KEEPALIVE_TIMEOUT};

    #gzip  on;
    charset utf-8;
    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};

    server {
        listen 80;
        listen [::]:80;

        server_name _ default;

        root /var/www/localhost/htdocs;

        index index.php index.html;

        location ~ ^/(status|ping)$ {
            log_subrequest off;
            access_log off;
            allow 127.0.0.1;
            deny all;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass ${NGINX_UPSTREAM};
        }

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~* \.(?:ico|gif|jpe?g|png|ttf|woff)$ {
            access_log off;
            expires 30d;
            add_header Pragma public;
            add_header Cache-Control "public, mustrevalidate, proxy-revalidate";
        }

        location ~ ^/(protected|framework|themes/\w+/views|\.|uploads/file) {
            deny all;
        }

        location ~ ^/(assets|static|themes|uploads) {
            expires 10d;
            add_header Cache-Control "public, no-transform";
        }

        location ~ \.php$ {
            try_files $uri =404;

            fastcgi_index index.php;
            fastcgi_split_path_info ^(.+\.php)(.*)$;

            #let yii catch the calls to unexisting PHP files
            set $fsn /index.php;
            if (-f $document_root$fastcgi_script_name){
                    set $fsn $fastcgi_script_name;
            }

            fastcgi_keep_conn on;
            include fastcgi_params;
            fastcgi_param PATH_INFO       $fastcgi_path_info;
            fastcgi_param SCRIPT_FILENAME $document_root$fsn;
            fastcgi_pass ${NGINX_UPSTREAM};
        }

        location ~ /\.ht {
            deny all;
        }

        location /protected {
            deny all;
        }

        location /uploads/file {
            deny all;
        }
    }
}
```

**Comment by s2074135** [comment]
And here the corresponding docker-compose.yml:

```
version: '3.1'
services:
  humhub:
    restart: always
    image: mriedmann/humhub:1.6.3
    container_name: humhub
    hostname: humhub
    environment:
      # 1 => true, set to "false" to disable.
      HUMHUB_DB_USER: ${HUMHUB_DB_USER}
      HUMHUB_DB_PASSWORD: ${HUMHUB_DB_PASSWORD}
      HUMHUB_DB_HOST: 'db'
      HUMHUB_DB_NAME: 'humhub'
      HUMHUB_AUTO_INSTALL: 1
      HUMHUB_DEBUG: 1
      HUMHUB_PROTO: 'http'
      HUMHUB_HOST: humhum.com # alt.humhub.com 
      # Reverseproxy variables
      VIRTUAL_HOST: humhum.com # alt.humhumb.com
      # Let's encrpyt variables
      LETSENCRYPT_HOST: humhum.com # alt.humhub.com 
      LETSENCRYPT_EMAIL: admin@humhum.com
      NGINX_KEEPALIVE_TIMEOUT: '65'
      NGINX_CLIENT_MAX_BODY_SIZE: '10m'

    volumes:
      - '/opt/docker/humhub/data/humhub/protected/config:/var/www/localhost/htdocs/protected/config'
      - '/opt/docker/humhub/data/humhub/protected/modules:/var/www/localhost/htdocs/protected/modules'
      - '/opt/docker/humhub/data/humhub/uploads:/var/www/localhost/htdocs/uploads'
      - '/opt/docker/humhub/data/humhub/themes:/var/www/localhost/htdocs/themes/humhum'
      # Not strictly necessary, just to shut up the log file
      - '/opt/docker/humhub/data/humhub/protected/runtime/logs:/var/www/localhost/htdocs/protected/runtime/logs/'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coltero

  db:
    restart: always
    image: mariadb:latest
    container_name: mariadb
    hostname: humhub
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'humhub'
      MYSQL_USER: ${HUMHUB_DB_USER}
      MYSQL_PASSWORD: ${HUMHUB_DB_PASSWORD}
    volumes:
      - '/opt/docker/humhub/data/mariadb/:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coltero

networks:
  coltero:
    external: true

```
