### ISSUE TITLE
How to use SET_PJAX environment variable?

### ISSUE THREAD

**Issue by jimlinntu** [mriedmann/humhub-docker#164]
```yml
version: '3.1'
services:
  humhub:
    image: mriedmann/humhub:1.6.2
    ports:
      - "8080:80"
    volumes:
      - "./config:/var/www/localhost/htdocs/protected/config"
      - "./uploads:/var/www/localhost/htdocs/uploads"
      - "./modules:/var/www/localhost/htdocs/protected/modules"
    environment:
      HUMHUB_DB_USER: humhub
      HUMHUB_DB_PASSWORD: humhub
      SET_PJAX: "true"
    depends_on:
      - db

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: humhub
      MYSQL_USER: humhub
      MYSQL_PASSWORD: humhub
    volumes:
      - "./db/:/var/lib/mysql"
```

I tried to set `SET_PJAX` like this, but it seems not working:
In `/var/www/localhost/htdocs/protected/config/common.php`, `enablePjax` is still false.

```php
<?php
/**
 * This file provides to overwrite the default HumHub / Yii configuration by your local common (Console and Web) environments
 * @see http://www.yiiframework.com/doc-2.0/guide-concept-configurations.html
 * @see http://docs.humhub.org/admin-installation-configuration.html
 * @see http://docs.humhub.org/dev-environment.html
 */
return [
	'params' => [
        'enablePjax' => false
    ],
    'components' => [
        'urlManager' => [
            'showScriptName' => false,
            'enablePrettyUrl' => true,
        ],
    ]
];
```
