### ISSUE TITLE
Cache has wrong permissions

### ISSUE THREAD

**Issue by alexhorn** [mriedmann/humhub-docker#194]
When trying to save settings (e.g. global time zone), the following error is shown:
```
Uuuups ... Du hast womöglich den falschen Weg eingeschlagen.
Es ist ein interner Fehler aufgetreten.
```

The logs show this error:
```
humhub_1  | 2021-04-26 12:27:38 [172.18.0.2][-][-][warning][yii\caching\FileCache::setValue] Unable to write cache file '/var/www/localhost/htdocs/protected/runtime/cache/55/humhub55faa527c8996473568237dc780d430d.bin': file_put_contents(/var/www/localhost/htdocs/protected/runtime/cache/55/humhub55faa527c8996473568237dc780d430d.bin): failed to open stream: Permission denied
```

Apparently the permission files are owned by root and are set to 644 so that the PHP process can not access them.

Did we do something wrong?

**Comment by mriedmann** [comment]
Hi and thx for your Report.

Sadly, I can't reproduce your error. Can you please post the Humhub version, Image version (Hash or Tag) and Conteiner-Config (docker-compose or docker-command you used to start).

**Comment by alexhorn** [comment]
We are running HumHub 1.8.1 from the `mriedmann/humhub:1.8` image.

Here's our `docker-compose.yml`:

```
version: '3.1'
services:
  humhub:
    image: mriedmann/humhub:1.8
    restart: always
    links:
      - "db:db"
    volumes:
      - ./humhub_config:/var/www/localhost/htdocs/protected/config
      - ./humhub_uploads:/var/www/localhost/htdocs/uploads
      - ./humhub_modules:/var/www/localhost/htdocs/protected/modules
    environment:
      HUMHUB_DB_USER: humhub
      HUMHUB_DB_PASSWORD: redacted
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.humhub.rule=Host(`redacted`)"
      - "traefik.http.routers.humhub.entrypoints=https"
      - "traefik.http.routers.humhub.tls=true"
      - "traefik.http.routers.humhub.tls.certresolver=le"
    networks:
      - web
      - internal

  db:
    image: mariadb:10.2
    restart: always
    volumes:
      - ./humhub_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: redacted
      MYSQL_DATABASE: humhub
      MYSQL_USER: humhub
      MYSQL_PASSWORD: redacted
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    external: false
```
