### ISSUE TITLE
Custom Themes/Modules/Config with Docker Compose file

### ISSUE THREAD

**Issue by theobouwman** [mriedmann/humhub-docker#225]
Hi,

this is my docker compose file: 

```
version: '3.1'
services:
  humhub:
    image: mriedmann/humhub:stable
    links:
      - "db:db"
    ports:
      - "8080:80"
    volumes:
      - "config:/var/www/localhost/htdocs/protected/config"
      - "uploads:/var/www/localhost/htdocs/uploads"
      - "modules:/var/www/localhost/htdocs/protected/modules"
      - "themes:/var/www/localhost/htdocs/themes"
    environment:
      HUMHUB_DB_USER: humhub
      HUMHUB_DB_PASSWORD: humhub

  db:
    image: mariadb:10.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: humhub
      MYSQL_USER: humhub
      MYSQL_PASSWORD: humhub

volumes:
  config: {}
  uploads: {}
  modules: {}
  themes: {}
```

This file is stored in a git repo with this structure:
```
docker-compose.yml
themes/MyCustomTheme
modules/MyModule1
uploads/DefaultUpload1
config/
```

How would I let docker compose know to use the custom themes, modules, uploads and config when starting the containers?

Thanks in advance.
