### ISSUE TITLE
Cannot upgrade to 1.9.2

### ISSUE THREAD

**Issue by timaschew** [mriedmann/humhub-docker#227]
First of all thank you so much for your work!
I've used the docker-compose file in your repository and pinned the version for your humhub image to 1.8.3

Start/installation was smooth. Then I've added the auto update module and started to upgrade.
I've installed and activated some other modules as well before!

It failed, here is the log:

```
humhub_1  | 2021-10-17 14:47:46 [172.19.0.1][1][li1avf1a4sdg65to96bbmol18p][error][yii\base\ErrorException:2] yii\base\ErrorException: rename(): The first argument to copy() function cannot be a directory in /var/www/localhost/htdocs/protected/modules/updater/libs/UpdatePackage.php:151
humhub_1  | Stack trace:
humhub_1  | #0 [internal function]: yii\base\ErrorHandler->handleError()
humhub_1  | #1 /var/www/localhost/htdocs/protected/modules/updater/libs/UpdatePackage.php(151): rename()
humhub_1  | #2 /var/www/localhost/htdocs/protected/modules/updater/modules/packageinstaller/controllers/InstallController.php(71): humhub\modules\updater\libs\UpdatePackage->install()
humhub_1  | #3 [internal function]: humhub\modules\updater\modules\packageinstaller\controllers\InstallController->actionInstallFiles()
humhub_1  | #4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
humhub_1  | #5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
humhub_1  | #6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
humhub_1  | #7 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
humhub_1  | #8 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
humhub_1  | #9 /var/www/localhost/htdocs/index.php(25): yii\base\Application->run()
humhub_1  | #10 {main}
humhub_1  | 2021-10-17 14:47:46 [172.19.0.1][1][li1avf1a4sdg65to96bbmol18p][info][application] $_GET = []
humhub_1  |
humhub_1  | $_SERVER = [
humhub_1  |     'USER' => 'nginx'
humhub_1  |     'HOME' => '/var/lib/nginx'
humhub_1  |     'HTTP_COOKIE' => '_csrf=296f297648bc1315ca4b08c93241a04a99c41c1092e80aa207b3e9436a6e4aeca%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22pGRUXXe1LacNc84nHv6rCyRZkWGCQKUQ%22%3B%7D; PHPSESSID=li1avf1a4sdg65to96bbmol18p; _identity=18399ca1a889d62a64f437143036b6c47cc1bad83d0ef2187c8e1bfdcf21074ea%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A50%3A%22%5B1%2C%22156467fa-53c7-4f7f-a91b-6b8c2a708478%22%2C2592000%5D%22%3B%7D'
humhub_1  |     'HTTP_CONNECTION' => 'keep-alive'
humhub_1  |     'HTTP_REFERER' => 'http://localhost:8080/updater/update'
humhub_1  |     'HTTP_SEC_GPC' => '1'
humhub_1  |     'HTTP_DNT' => '1'
humhub_1  |     'HTTP_SEC_FETCH_SITE' => 'same-origin'
humhub_1  |     'HTTP_SEC_FETCH_MODE' => 'cors'
humhub_1  |     'HTTP_SEC_FETCH_DEST' => 'empty'
humhub_1  |     'HTTP_ORIGIN' => 'http://localhost:8080'
humhub_1  |     'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
humhub_1  |     'HTTP_X_CSRF_TOKEN' => 'T8e2yx3iZeCCaaAL0-DgdmlXsm_0AqYpymcOIcv4G98_gOSeRboA0c4Iw0Ww2NQYISGEHbd79HOhMElimrNOjg=='
humhub_1  |     'HTTP_CONTENT_LENGTH' => '31'
humhub_1  |     'HTTP_CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8'
humhub_1  |     'HTTP_ACCEPT_ENCODING' => 'gzip, deflate'
humhub_1  |     'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5'
humhub_1  |     'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01'
humhub_1  |     'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0'
humhub_1  |     'HTTP_HOST' => 'localhost:8080'
humhub_1  |     'SCRIPT_FILENAME' => '/var/www/localhost/htdocs/index.php'
humhub_1  |     'PATH_INFO' => ''
humhub_1  |     'REDIRECT_STATUS' => '200'
humhub_1  |     'SERVER_NAME' => '_'
humhub_1  |     'SERVER_PORT' => '80'
humhub_1  |     'SERVER_ADDR' => '172.19.0.5'
humhub_1  |     'REMOTE_PORT' => '56766'
humhub_1  |     'REMOTE_ADDR' => '172.19.0.1'
humhub_1  |     'SERVER_SOFTWARE' => 'nginx/1.20.1'
humhub_1  |     'GATEWAY_INTERFACE' => 'CGI/1.1'
humhub_1  |     'REQUEST_SCHEME' => 'http'
humhub_1  |     'SERVER_PROTOCOL' => 'HTTP/1.1'
humhub_1  |     'DOCUMENT_ROOT' => '/var/www/localhost/htdocs'
humhub_1  |     'DOCUMENT_URI' => '/index.php'
humhub_1  |     'REQUEST_URI' => '/package-installer/install/install-files'
humhub_1  |     'SCRIPT_NAME' => '/index.php'
humhub_1  |     'CONTENT_LENGTH' => '31'
humhub_1  |     'CONTENT_TYPE' => 'application/x-www-form-urlencoded; charset=UTF-8'
humhub_1  |     'REQUEST_METHOD' => 'POST'
humhub_1  |     'QUERY_STRING' => ''
humhub_1  |     'FCGI_ROLE' => 'RESPONDER'
humhub_1  |     'PHP_SELF' => '/index.php'
humhub_1  |     'REQUEST_TIME_FLOAT' => 1634482066.2993
humhub_1  |     'REQUEST_TIME' => 1634482066
humhub_1  | ]
humhub_1  | - -  17/Oct/2021:14:47:50 +0000 "GET /index.php" 200
humhub_1  | - -  17/Oct/2021:14:48:06 +0000 "GET /index.php" 200
```

Not sure if this should go to this project or the original humhub.

**Comment by timaschew** [comment]
I forgot to mention that I'm running it not in produciton mode, at least I see this message on the admin info page:

```
HumHub is currently in debug mode. Disable it when running on production!
See installation manual for more details. 
```
I've created a new fresh setup with humhub 1.8.3 (without any modules, etc.)

I've prepended to my docker-compose.yml this service:

```
  humhub-new:
    image: docker.io/mriedmann/humhub:1.9
    ports:
      - "8081:80"
    environment:
      HUMHUB_DB_USER: 'DB_USER'
      HUMHUB_DB_PASSWORD: 'DB_PASSWORD'
      HUMHUB_DB_HOST: 'db'
      HUMHUB_DB_NAME: 'humhub'
      HUMHUB_AUTO_INSTALL: 1
      HUMHUB_DEBUG: 1
      HUMHUB_PROTO: 'http'
      HUMHUB_HOST: 'localhost'
      # Mailer install setup
      HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS: 'noreply@example.com'
      HUMHUB_MAILER_SYSTEM_EMAIL_NAME: 'HumHub'
      HUMHUB_MAILER_TRANSPORT_TYPE: 'smtp'
      HUMHUB_MAILER_HOSTNAME: 'mailer'
      HUMHUB_MAILER_PORT: 1025
      #HUMHUB_MAILER_USERNAME:
      #HUMHUB_MAILER_PASSWORD:
      #HUMHUB_MAILER_ENCRYPTION:
      HUMHUB_MAILER_ALLOW_SELF_SIGNED_CERTS: 0
      # Cache Config
      HUMHUB_CACHE_EXPIRE_TIME: 3600
      HUMHUB_CACHE_CLASS: yii\redis\Cache
      HUMHUB_QUEUE_CLASS: humhub\modules\queue\driver\Redis
      HUMHUB_REDIS_HOSTNAME: redis
      HUMHUB_REDIS_PORT: 6379
      HUMHUB_REDIS_PASSWORD: redis_password
    volumes:
      - "/Users/me/dev/humhub-docker/config:/var/www/localhost/htdocs/protected/config"
```
I've omitted the health check.
Then I run `docker-compose up` and printed the container via `docker ps` and entered the container with humhub 1.9 via 
`docker exec -it 275d32726221 sh`.
Inside the container I run this:

```
/ # cd /var/www/localhost/htdocs/protected/
/var/www/localhost/htdocs/protected # INSTALL_VERSION=$(cat /var/www/localhost/htdocs/protected/config/.version)
/var/www/localhost/htdocs/protected # SOURCE_VERSION=$(cat /usr/src/humhub/.version)
/var/www/localhost/htdocs/protected # echo $INSTALL_VERSION
v1.9.1
/var/www/localhost/htdocs/protected # echo $SOURCE_VERSION
v1.9.1
/var/www/localhost/htdocs/protected # SOURCE_VERSION=v.1.8.3
/var/www/localhost/htdocs/protected # php yii migrate/up --includeModuleMigrations=1 --interactive=0
Yii Migration Tool (based on Yii v2.0.40)

No new migrations found. Your system is up-to-date.
```
