### ISSUE TITLE
Permissions - Profile Image

### ISSUE THREAD

**Issue by r1z1** [mriedmann/humhub-docker#264]
Hi,

I have this error during the prerequisites step from a fresh docker install (using portainer.io):

`Permissions - Profile Image (Hint: Make /var/www/localhost/htdocs/uploads/profile_image writable for the Webserver/PHP!)`

My docker-compose

```
version: '3.1'
services:
  humhub:
    image: mriedmann/humhub:stable
    links:
      - "db:db"
    ports:
      - "8080:80"
    volumes:
      - "config:/var/www/localhost/htdocs/protected/config"
      - "uploads:/var/www/localhost/htdocs/uploads"
      - "modules:/var/www/localhost/htdocs/protected/modules"
    environment:
      HUMHUB_DB_USER: humhub
      HUMHUB_DB_PASSWORD: humhub
  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: humhub
      MYSQL_USER: humhub
      MYSQL_PASSWORD: humhub
```

If it helps:
![image](https://user-images.githubusercontent.com/4463593/165865002-e96b17a8-de9f-4f50-9fcd-1e83b8bc7aa4.png)

Thx

**Comment by zarevskaya** [comment]
Hi,

You must create the folde called **profile_image** in uploads.

**Comment by r1z1** [comment]
Hi,

The folder exists and seems to have the correct permissions

`drwxrwxr-x` 3 systemd-network systemd-journal 4096 Apr 25 05:02 profile_image`

**Comment by zarevskaya** [comment]
> Hi,
> 
> The folder exists and seems to have the correct permissions
> 
> `drwxrwxr-x` 3 systemd-network systemd-journal 4096 Apr 25 05:02 profile_image`

Okay, change the image by; mriedmann/humhub:1.9

I remember this trick ^^

**Comment by mriedmann** [comment]
It depends a bit on your system. What distribution are you on? Is it possible that SELinux or AppArmor is blocking the requests? Also, please have a look inside the container (`docker exec -it <containername> sh`) and run `id` to get the current user-id. If it is not 0 (=root) or whatever id systemd-network or systemd-journal has on your system it is unable to write to the directory. 

Things you can try: 

- Go inside the container, navigate to the volume and try to create a file manually (`touch testfile.txt`). If that works it cannot be a SELinux (or similar) or container-engine Problem. It is most likely some issue with the application itself or its configuration.
- Set `chmod -R +rwX <path>` to allow everyone on the system access. If this solves the problem your access-rules are incorrect. Try to find the right user-id the application/container is using and set it as owner (`chown -R <userid> <path>`)
- Check `df` and `mount` if you see anything suspicious going on
- Post your `uname -a` `cat /etc/os-release` and `docker info` output here (please remove sensitive information beforehand)

Hope we can get this working for you ;)

**Comment by mriedmann** [comment]
Ok very weird, no idea sorry ... I will try to replicate this on my side ... but could take some time.

**Comment by francoisauclair911** [comment]
Having the same issue running humbub `1.11.4`

**Comment by ThunderM16** [comment]
issues still an ongoing issue and went stale do to inactivity which should of never happened

**Comment by mriedmann** [comment]
Sorry reopening then

**Comment by ThunderM16** [comment]
i would like to state i got a stable version of it running for docker and will update the compose files here im currently working on a 3rd party app store repo for the OS known as https://casaos.io which utilizes Docker and Docker-Compose to run files check out more @ https://cloudrack.ca (this is a domain which links cname to my github.io pages https://thunderm16.github.io/Cloudrack-CasaOS-App-Repo/)

I will post the humhub configs needed to run in time sorry seems i lost the files and need to re-run it as this was a app i was planning on adding to my 3rd party app repo and just havent gotten back to it yet.

**Comment by ThunderM16** [comment]
stable works for sure but heres what i have for a casaos yaml im sure it be simple to configure as its still a docker-compose.yaml

```yaml
name: festive_john
services:
  db:
    cpu_shares: 90
    command: []
    container_name: db
    deploy:
      resources:
        limits:
          memory: 15981M
    environment:
      - MYSQL_DATABASE=humhub
      - MYSQL_PASSWORD=humhub
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=humhub
    image: mariadb:10.2
    labels:
      icon: https://products.containerize.com/social-network-platforms/humhub/menu_image.png
    ports:
      - target: 3306
        published: "3306"
        protocol: tcp
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
  humhub:
    cpu_shares: 90
    command: []
    container_name: humhub
    depends_on:
      db:
        condition: service_started
        restart: true
        required: true
    deploy:
      resources:
        limits:
          memory: 15981M
    environment:
      - HUMHUB_DB_HOST=db:3306
      - HUMHUB_DB_PASSWORD=humhub
      - HUMHUB_DB_USER=humhub
    image: mriedmann/humhub:stable
    labels:
      icon: https://products.containerize.com/social-network-platforms/humhub/menu_image.png
    links:
      - db:db
    ports:
      - target: 80
        published: "8081"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/var/www/localhost/htdocs/protected/config
        target: /var/www/localhost/htdocs/protected/config
      - type: bind
        source: /DATA/AppData/var/www/localhost/htdocs/uploads
        target: /var/www/localhost/htdocs/uploads
      - type: bind
        source: /DATA/AppData/var/www/localhost/htdocs/protected/modules
        target: /var/www/localhost/htdocs/protected/modules
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: 10.0.0.202
  icon: https://products.containerize.com/social-network-platforms/humhub/menu_image.png
  index: /
  port_map: "8081"
  scheme: http
  store_app_id: festive_john
  title:
    custom: HumHub
```
