### ISSUE TITLE
Issue with email delivery when creating new accounts and others

### ISSUE THREAD

**Issue by andresgarcia0313** [mriedmann/humhub-docker#352]
Hi,

I wanted to inform you that I'm experiencing issues with sending emails in the compose when creating new accounts; the email doesn't arrive. I ruled out SMTP configuration problems since I've successfully used the same Gmail SMTP configuration and application password in other software. Could you please check if there's any issue with the configuration or any restriction in the Docker image? I appreciate your help and consideration in this matter. Thank you!

Best regards, 

Andrés García

environment:
      HUMHUB_DB_USER: humhub
      HUMHUB_DB_PASSWORD: humhub
      HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS: 'gestion.mejorada@gmail.com'
      HUMHUB_MAILER_SYSTEM_EMAIL_NAME: 'HumHub'
      HUMHUB_MAILER_TRANSPORT_TYPE: 'smtp'
      HUMHUB_MAILER_HOSTNAME: 'smtp.gmail.com'
      HUMHUB_MAILER_PORT: 587
      HUMHUB_MAILER_USERNAME: 'gestion.mejorada@gmail.com'
      HUMHUB_MAILER_PASSWORD: '********'
      HUMHUB_MAILER_ENCRYPTION: 'tls'
      NGINX_KEEPALIVE_TIMEOUT: 480
      PHP_MAX_EXECUTION_TIME: 480
      
      
    the entire file compose:
    
    
version: '3.8'

services:
  humhub:
    image: mriedmann/humhub:stable
    ports:
      - "89:80"
    volumes:
      - "./config:/var/www/localhost/htdocs/protected/config"
      - "./uploads:/var/www/localhost/htdocs/uploads"
      - "./uploads/profile_image:/var/www/localhost/htdocs/uploads/profile_image"
      - "./modules:/var/www/localhost/htdocs/protected/modules"
    environment:
      HUMHUB_DB_USER: humhub
      HUMHUB_DB_PASSWORD: humhub
      HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS: 'gestion.mejorada@gmail.com'
      HUMHUB_MAILER_SYSTEM_EMAIL_NAME: 'HumHub'
      HUMHUB_MAILER_TRANSPORT_TYPE: 'smtp'
      HUMHUB_MAILER_HOSTNAME: 'smtp.gmail.com'
      HUMHUB_MAILER_PORT: 587
      HUMHUB_MAILER_USERNAME: 'gestion.mejorada@gmail.com'
      HUMHUB_MAILER_PASSWORD: '********'
      HUMHUB_MAILER_ENCRYPTION: 'tls'
      NGINX_KEEPALIVE_TIMEOUT: 480
      PHP_MAX_EXECUTION_TIME: 480
    restart: unless-stopped

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: humhub
      MYSQL_USER: humhub
      MYSQL_PASSWORD: humhub
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
volumes:
  config:
  uploads:
  modules:

**Comment by andresgarcia0313** [comment]
This worked for me, it seems the web config didn't work well on a slow server.

```

version: '3.8'

services:
  humhub:
    image: mriedmann/humhub:stable
    ports:
      - "89:80"
    volumes:
      - "./config:/var/www/localhost/htdocs/protected/config"
      - "./uploads:/var/www/localhost/htdocs/uploads"
      - "./uploads/profile_image:/var/www/localhost/htdocs/uploads/profile_image"
      - "./modules:/var/www/localhost/htdocs/protected/modules"
    environment:
      HUMHUB_DB_USER: humhub
      HUMHUB_DB_PASSWORD: humhub
      HUMHUB_DB_HOST: db
      HUMHUB_DB_NAME: humhub
      HUMHUB_AUTO_INSTALL: 1
      HUMHUB_ADMIN_LOGIN: admin
      HUMHUB_ADMIN_PASSWORD: ********
      WAIT_FOR_DB: 1
      HUMHUB_DEBUG: 1
      HUMHUB_PROTO: https
      HUMHUB_HOST: localhost
      HUMHUB_MAILER_SYSTEM_EMAIL_ADDRESS: 'gestion.mejorada@gmail.com'
      HUMHUB_MAILER_SYSTEM_EMAIL_NAME: 'HumHub'
      HUMHUB_MAILER_TRANSPORT_TYPE: 'smtp'
      HUMHUB_MAILER_HOSTNAME: 'smtp.gmail.com'
      HUMHUB_MAILER_PORT: 587
      HUMHUB_MAILER_USERNAME: 'gestion.mejorada@gmail.com'
      HUMHUB_MAILER_PASSWORD: '*******'
      HUMHUB_MAILER_ENCRYPTION: 'tls'
      NGINX_KEEPALIVE_TIMEOUT: 480
      PHP_MAX_EXECUTION_TIME: 480
      TZ: America/Bogota
    restart: unless-stopped

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: ********
      MYSQL_DATABASE: humhub
      MYSQL_USER: humhub
      MYSQL_PASSWORD: ********
      TZ: America/Bogota
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
volumes:
  config:
  uploads:
  modules:
```
