### ISSUE TITLE
Performance issues with HumHub on k8s (Scaleway dev-1m node)

### ISSUE THREAD

**Issue by vilmosnagy** [mriedmann/humhub-docker#378]
Hi,

I'm not sure if this is the right place to ask for help or start a discussion, but I couldn’t find a better venue—so apologies in advance if this isn't appropriate.

I'm running a HumHub instance on Kubernetes (Scaleway, `dev-1m` node: 3 vCPUs, 4 GB RAM). Only HumHub and its MariaDB instance are running on the node (besides minimal Kubernetes system pods).

Here’s a simplified config of the HumHub container:

```yaml
containers:
- name: humhub
  image: mriedmann/humhub:1.17.1
  env:
    - name: PHP_UPLOAD_MAX_FILESIZE
      value: 90M
    - name: PHP_POST_MAX_SIZE
      value: 100M
    - name: NGINX_CLIENT_MAX_BODY_SIZE
      value: 95M
    - name: HUMHUB_DB_USER
      value: <...>
    - name: HUMHUB_DB_PASSWORD
      value: <...>
    - name: HUMHUB_DB_NAME
      value: <...>
    - name: HUMHUB_DB_HOST
      value: mariadb.mariadb.svc
  livenessProbe:
    httpGet:
      path: /
      port: http
      scheme: HTTP
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
```

The problem:
 - HumHub feels very slow, despite the relatively light load:
 - Page loads are sluggish.
 - Notifications take a long time to appear.
 - My wife cannot upload videos from her phone (while I can upload the same video from my laptop). 

I’m not familiar with PHP-based apps, so I’m not sure where to look for bottlenecks (PHP config, NGINX, HumHub settings, etc.). I’m happy to share logs, metrics, or other details if needed.

Any ideas on what I could investigate or try?

Thanks in advance!

Best regards,
Vilmos
