### ISSUE TITLE
Issue with Environment Variable NGINX_CLIENT_MAX_BODY_SIZE

### ISSUE THREAD

**Issue by maglite4cell** [mriedmann/humhub-docker#91]
Changing the Environment Variable NGINX_CLIENT_MAX_BODY_SIZE does not update the Nginx config file

**Comment by maglite4cell** [comment]
Missed Spacing in Variable

**Comment by olekristensen** [comment]
hi, how did you solve it, do you need a space between number and unit?
`100 m` indstead of `100m`

**Comment by ArchBlood** [comment]
If you follow the NGINX docs shouldn't need a space.
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by mriedmann** [comment]
@olekristensen have you tried the value in humhub-settings like ArchBlood in issue #92 suggested?
https://github.com/mriedmann/humhub-docker/issues/92#issuecomment-622239006
It could be possible to set this by manipulating the config file directly, but I do not have any time at the moment. A PR would be highly appreciated :)

**Comment by ArchBlood** [comment]
I don't know much about NGINX so I can give an example. :thinking:

https://github.com/mriedmann/humhub-docker/blob/712aae01b10d527219c9e9facf1cb7b2b67a101b/etc/nginx/nginx.conf#L34

```nginx
    client_max_body_size size;
    client_max_body_size 100m;
```
As `NGINX_CLIENT_MAX_BODY_SIZE` is seen as `1m` as this is the default value.

**Comment by mriedmann** [comment]
Just tested it. To raise the upload-limit you have to set all 3 env-vars `NGINX_CLIENT_MAX_BODY_SIZE`, `PHP_POST_MAX_SIZE` and `PHP_UPLOAD_MAX_FILESIZE`. Also use `M` for PHP and `m` for nginx do avoid problems. Do **not** seperate the number from the unit (e.g. `100 m`). 
```
version: '3.1'
services:
  humhub:
    image: mriedmann/humhub:latest
    ports:
      - "8080:80"
    environment:
      NGINX_CLIENT_MAX_BODY_SIZE: 50m
      PHP_UPLOAD_MAX_FILESIZE: 50M
      PHP_POST_MAX_SIZE: 50M
```

I can totally see why this is confusing. If I find some time I can introduce a variable that can be used to change all 3 values at once.
